/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 25, 2010 7:09:56 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * AttachData generated by hbm2java
 */
@Entity
@Table(name = "attach_data")
@SuppressWarnings("serial")
public class AttachmentData implements java.io.Serializable {

	private int id;
	private Attachment attachment;
	private byte[] thedata;

	public AttachmentData() {
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Attachment getAttachment() {
		return this.attachment;
	}

	public void setAttachment(Attachment attachment) {
		this.attachment = attachment;
	}

	@Column(name = "thedata", nullable = false)
	public byte[] getThedata() {
		return this.thedata;
	}

	public void setThedata(byte[] thedata) {
		this.thedata = thedata;
	}

	@PrePersist
	public void prePersist() {
		if (id == 0) {
			setId(getAttachment().getId());
		}
	}
}
