/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Arrays;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BzSchemaId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class BzSchemaId implements java.io.Serializable {

	private byte[] schemaData;
	private BigDecimal version;

	public BzSchemaId() {
	}

	public BzSchemaId(byte[] schemaData, BigDecimal version) {
		this.schemaData = schemaData;
		this.version = version;
	}

	@Column(name = "schema_data", nullable = false)
	public byte[] getSchemaData() {
		return this.schemaData;
	}

	public void setSchemaData(byte[] schemaData) {
		this.schemaData = schemaData;
	}

	@Column(name = "version", nullable = false, precision = 3)
	public BigDecimal getVersion() {
		return this.version;
	}

	public void setVersion(BigDecimal version) {
		this.version = version;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BzSchemaId))
			return false;
		BzSchemaId castOther = (BzSchemaId) other;

		return ((this.getSchemaData() == castOther.getSchemaData()) || (this.getSchemaData() != null
				&& castOther.getSchemaData() != null && Arrays.equals(this.getSchemaData(), castOther.getSchemaData())))
				&& ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null
						&& castOther.getVersion() != null && this.getVersion().equals(castOther.getVersion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSchemaData() == null ? 0 : Arrays.hashCode(this.getSchemaData()));
		result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
		return result;
	}

}
