/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryGroupMapId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class CategoryGroupMapId implements java.io.Serializable {

	private short categoryId;
	private int groupId;

	public CategoryGroupMapId() {
	}

	public CategoryGroupMapId(short categoryId, int groupId) {
		this.categoryId = categoryId;
		this.groupId = groupId;
	}

	@Column(name = "category_id", nullable = false)
	public short getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(short categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "group_id", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryGroupMapId))
			return false;
		CategoryGroupMapId castOther = (CategoryGroupMapId) other;

		return (this.getCategoryId() == castOther.getCategoryId()) && (this.getGroupId() == castOther.getGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCategoryId();
		result = 37 * result + this.getGroupId();
		return result;
	}

}
