/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComponentCcId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class ComponentCcId implements java.io.Serializable {

	private int userId;
	private short componentId;

	public ComponentCcId() {
	}

	public ComponentCcId(int userId, short componentId) {
		this.userId = userId;
		this.componentId = componentId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "component_id", nullable = false)
	public short getComponentId() {
		return this.componentId;
	}

	public void setComponentId(short componentId) {
		this.componentId = componentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComponentCcId))
			return false;
		ComponentCcId castOther = (ComponentCcId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getComponentId() == castOther.getComponentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getComponentId();
		return result;
	}

}
