/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DependenciesId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class DependencyId implements java.io.Serializable {

	private int blocked;
	private int dependson;

	public DependencyId() {
	}

	public DependencyId(int blocked, int dependson) {
		this.blocked = blocked;
		this.dependson = dependson;
	}

	@Column(name = "blocked", nullable = false)
	public int getBlocked() {
		return this.blocked;
	}

	public void setBlocked(int blocked) {
		this.blocked = blocked;
	}

	@Column(name = "dependson", nullable = false)
	public int getDependson() {
		return this.dependson;
	}

	public void setDependson(int dependson) {
		this.dependson = dependson;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DependencyId))
			return false;
		DependencyId castOther = (DependencyId) other;

		return (this.getBlocked() == castOther.getBlocked()) && (this.getDependson() == castOther.getDependson());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBlocked();
		result = 37 * result + this.getDependson();
		return result;
	}

	public String toString() {
		return blocked + "-" + dependson;
	}

}
