/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NamedqueriesLinkInFooterId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class NamedqueryLinkInFooterId implements java.io.Serializable {

	private int namedqueryId;
	private int userId;

	public NamedqueryLinkInFooterId() {
	}

	public NamedqueryLinkInFooterId(int namedqueryId, int userId) {
		this.namedqueryId = namedqueryId;
		this.userId = userId;
	}

	@Column(name = "namedquery_id", nullable = false)
	public int getNamedqueryId() {
		return this.namedqueryId;
	}

	public void setNamedqueryId(int namedqueryId) {
		this.namedqueryId = namedqueryId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NamedqueryLinkInFooterId))
			return false;
		NamedqueryLinkInFooterId castOther = (NamedqueryLinkInFooterId) other;

		return (this.getNamedqueryId() == castOther.getNamedqueryId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNamedqueryId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
