/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfilesActivityId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class ProfileActivityId implements java.io.Serializable {

	private int userid;
	private int who;
	private Date profilesWhen;
	private int fieldid;
	private String oldvalue;
	private String newvalue;

	public ProfileActivityId() {
	}

	public ProfileActivityId(int userid, int who, Date profilesWhen, int fieldid) {
		this.userid = userid;
		this.who = who;
		this.profilesWhen = profilesWhen;
		this.fieldid = fieldid;
	}

	public ProfileActivityId(int userid, int who, Date profilesWhen, int fieldid, String oldvalue, String newvalue) {
		this.userid = userid;
		this.who = who;
		this.profilesWhen = profilesWhen;
		this.fieldid = fieldid;
		this.oldvalue = oldvalue;
		this.newvalue = newvalue;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "who", nullable = false)
	public int getWho() {
		return this.who;
	}

	public void setWho(int who) {
		this.who = who;
	}

	@Column(name = "profiles_when", nullable = false, length = 19)
	@Temporal(TemporalType.TIMESTAMP)
	public Date getProfilesWhen() {
		return this.profilesWhen;
	}

	public void setProfilesWhen(Date profilesWhen) {
		this.profilesWhen = profilesWhen;
	}

	@Column(name = "fieldid", nullable = false)
	public int getFieldid() {
		return this.fieldid;
	}

	public void setFieldid(int fieldid) {
		this.fieldid = fieldid;
	}

	@Column(name = "oldvalue")
	public String getOldvalue() {
		return this.oldvalue;
	}

	public void setOldvalue(String oldvalue) {
		this.oldvalue = oldvalue;
	}

	@Column(name = "newvalue")
	public String getNewvalue() {
		return this.newvalue;
	}

	public void setNewvalue(String newvalue) {
		this.newvalue = newvalue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProfileActivityId))
			return false;
		ProfileActivityId castOther = (ProfileActivityId) other;

		return (this.getUserid() == castOther.getUserid())
				&& (this.getWho() == castOther.getWho())
				&& ((this.getProfilesWhen() == castOther.getProfilesWhen()) || (this.getProfilesWhen() != null
						&& castOther.getProfilesWhen() != null && this.getProfilesWhen().equals(
						castOther.getProfilesWhen())))
				&& (this.getFieldid() == castOther.getFieldid())
				&& ((this.getOldvalue() == castOther.getOldvalue()) || (this.getOldvalue() != null
						&& castOther.getOldvalue() != null && this.getOldvalue().equals(castOther.getOldvalue())))
				&& ((this.getNewvalue() == castOther.getNewvalue()) || (this.getNewvalue() != null
						&& castOther.getNewvalue() != null && this.getNewvalue().equals(castOther.getNewvalue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + this.getWho();
		result = 37 * result + (getProfilesWhen() == null ? 0 : this.getProfilesWhen().hashCode());
		result = 37 * result + this.getFieldid();
		result = 37 * result + (getOldvalue() == null ? 0 : this.getOldvalue().hashCode());
		result = 37 * result + (getNewvalue() == null ? 0 : this.getNewvalue().hashCode());
		return result;
	}

}
