/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.eclipse.persistence.annotations.Convert;

/**
 * RepPlatform generated by hbm2java
 */
@Entity
@Table(name = "rep_platform", uniqueConstraints = @UniqueConstraint(columnNames = "value"))
@SuppressWarnings("serial")
public class RepPlatform implements java.io.Serializable {

	private Short id;
	private String value;
	private short sortkey;
	private boolean isactive;
	private Short visibilityValueId;

	public RepPlatform() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "value", unique = true, nullable = false, length = 64)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "sortkey", nullable = false)
	public short getSortkey() {
		return this.sortkey;
	}

	public void setSortkey(short sortkey) {
		this.sortkey = sortkey;
	}

	@Column(name = "isactive", nullable = false)
	@Convert("booleanToByte")
	public boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	@Column(name = "visibility_value_id")
	public Short getVisibilityValueId() {
		return this.visibilityValueId;
	}

	public void setVisibilityValueId(Short visibilityValueId) {
		this.visibilityValueId = visibilityValueId;
	}

}
