/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.eclipse.persistence.annotations.Convert;

/**
 * Setting generated by hbm2java
 */
@Entity
@Table(name = "setting")
@SuppressWarnings("serial")
public class Setting implements java.io.Serializable {

	private String name;
	private String defaultValue;
	private boolean isEnabled;
	private String subclass;
	private Set<ProfileSetting> profileSettings = new HashSet<ProfileSetting>(0);
	private Set<SettingValue> settingValues = new HashSet<SettingValue>(0);

	public Setting() {
	}

	@Id
	@Column(name = "name", unique = true, nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "default_value", nullable = false, length = 32)
	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	@Column(name = "is_enabled", nullable = false)
	@Convert("booleanToByte")
	public boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "subclass", length = 32)
	public String getSubclass() {
		return this.subclass;
	}

	public void setSubclass(String subclass) {
		this.subclass = subclass;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setting")
	public Set<ProfileSetting> getProfileSettings() {
		return this.profileSettings;
	}

	public void setProfileSettings(Set<ProfileSetting> profileSettings) {
		this.profileSettings = profileSettings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setting")
	public Set<SettingValue> getSettingValues() {
		return this.settingValues;
	}

	public void setSettingValues(Set<SettingValue> settingValues) {
		this.settingValues = settingValues;
	}

}
