/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TsError generated by hbm2java
 */
@Entity
@Table(name = "ts_error")
@SuppressWarnings("serial")
public class TsError implements java.io.Serializable {

	private TsErrorId id;

	public TsError() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "errorTime", column = @Column(name = "error_time", nullable = false)),
			@AttributeOverride(name = "jobid", column = @Column(name = "jobid", nullable = false)),
			@AttributeOverride(name = "message", column = @Column(name = "message", nullable = false)),
			@AttributeOverride(name = "funcid", column = @Column(name = "funcid", nullable = false)) })
	public TsErrorId getId() {
		return this.id;
	}

	public void setId(TsErrorId id) {
		this.id = id;
	}

}
