/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TsFuncmap generated by hbm2java
 */
@Entity
@Table(name = "ts_funcmap", uniqueConstraints = @UniqueConstraint(columnNames = "funcname"))
@SuppressWarnings("serial")
public class TsFuncmap implements java.io.Serializable {

	private Integer funcid;
	private String funcname;

	public TsFuncmap() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "funcid", unique = true, nullable = false)
	public Integer getFuncid() {
		return this.funcid;
	}

	public void setFuncid(Integer funcid) {
		this.funcid = funcid;
	}

	@Column(name = "funcname", unique = true, nullable = false)
	public String getFuncname() {
		return this.funcname;
	}

	public void setFuncname(String funcname) {
		this.funcname = funcname;
	}

}
