/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.eclipse.persistence.annotations.Convert;

/**
 * WhineQueries generated by hbm2java
 */
@Entity
@Table(name = "whine_queries")
@SuppressWarnings("serial")
public class WhineQuery implements java.io.Serializable {

	private Integer id;
	private WhineEvent whineEvents;
	private String queryName;
	private short sortkey;
	private boolean onemailperbug;
	private String title;

	public WhineQuery() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eventid", nullable = false)
	public WhineEvent getWhineEvents() {
		return this.whineEvents;
	}

	public void setWhineEvents(WhineEvent whineEvents) {
		this.whineEvents = whineEvents;
	}

	@Column(name = "query_name", nullable = false, length = 64)
	public String getQueryName() {
		return this.queryName;
	}

	public void setQueryName(String queryName) {
		this.queryName = queryName;
	}

	@Column(name = "sortkey", nullable = false)
	public short getSortkey() {
		return this.sortkey;
	}

	public void setSortkey(short sortkey) {
		this.sortkey = sortkey;
	}

	@Column(name = "onemailperbug", nullable = false)
	@Convert("booleanToByte")
	public boolean getOnemailperbug() {
		return this.onemailperbug;
	}

	public void setOnemailperbug(boolean onemailperbug) {
		this.onemailperbug = onemailperbug;
	}

	@Column(name = "title", nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
