/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WhineSchedules generated by hbm2java
 */
@Entity
@Table(name = "whine_schedules")
@SuppressWarnings("serial")
public class WhineSchedule implements java.io.Serializable {

	private Integer id;
	private WhineEvent whineEvents;
	private String runDay;
	private String runTime;
	private Date runNext;
	private int mailto;
	private short mailtoType;

	public WhineSchedule() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eventid", nullable = false)
	public WhineEvent getWhineEvents() {
		return this.whineEvents;
	}

	public void setWhineEvents(WhineEvent whineEvents) {
		this.whineEvents = whineEvents;
	}

	@Column(name = "run_day", length = 32)
	public String getRunDay() {
		return this.runDay;
	}

	public void setRunDay(String runDay) {
		this.runDay = runDay;
	}

	@Column(name = "run_time", length = 32)
	public String getRunTime() {
		return this.runTime;
	}

	public void setRunTime(String runTime) {
		this.runTime = runTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "run_next", length = 19)
	public Date getRunNext() {
		return this.runNext;
	}

	public void setRunNext(Date runNext) {
		this.runNext = runNext;
	}

	@Column(name = "mailto", nullable = false)
	public int getMailto() {
		return this.mailto;
	}

	public void setMailto(int mailto) {
		this.mailto = mailto;
	}

	@Column(name = "mailto_type", nullable = false)
	public short getMailtoType() {
		return this.mailtoType;
	}

	public void setMailtoType(short mailtoType) {
		this.mailtoType = mailtoType;
	}

}
