/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.eclipse.persistence.annotations.Convert;

/**
 * Attachments generated by hbm2java
 */
@Entity
@Table(name = "attachments")
@SuppressWarnings("serial")
public class Attachment extends AbstractIdentified<Integer> implements java.io.Serializable {

	private Integer attachId;
	private Profile profiles;
	private Task bugs;
	private Date creationTs;
	private Date modificationTime;
	private String description;
	private String mimetype;
	private Byte ispatch;
	private String filename;
	private boolean isobsolete;
	private boolean isprivate;
	private boolean isurl;
	private Set<Flags> flagses = new HashSet<Flags>(0);
	private Set<TaskActivity> taskActivities = new HashSet<TaskActivity>(0);
	private AttachmentData attachData;

	public Attachment() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "attach_id", unique = true, nullable = false)
	@Override
	public Integer getId() {
		return this.attachId;
	}

	@Override
	public void setId(Integer attachId) {
		this.attachId = attachId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "submitter_id", nullable = false)
	public Profile getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Profile profiles) {
		this.profiles = profiles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bug_id", nullable = false)
	public Task getBugs() {
		return this.bugs;
	}

	public void setBugs(Task bugs) {
		this.bugs = bugs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_ts", nullable = false, length = 19)
	public Date getCreationTs() {
		return this.creationTs;
	}

	public void setCreationTs(Date creationTs) {
		this.creationTs = creationTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modification_time", nullable = false, length = 19)
	public Date getModificationTime() {
		return this.modificationTime;
	}

	public void setModificationTime(Date modificationTime) {
		this.modificationTime = modificationTime;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "mimetype", nullable = false)
	public String getMimetype() {
		return this.mimetype;
	}

	public void setMimetype(String mimetype) {
		this.mimetype = mimetype;
	}

	@Column(name = "ispatch")
	public Byte getIspatch() {
		return this.ispatch;
	}

	public void setIspatch(Byte ispatch) {
		this.ispatch = ispatch;
	}

	@Column(name = "filename", nullable = false, length = 100)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "isobsolete", nullable = false)
	@Convert("booleanToByte")
	public boolean getIsobsolete() {
		return this.isobsolete;
	}

	public void setIsobsolete(boolean isobsolete) {
		this.isobsolete = isobsolete;
	}

	@Column(name = "isprivate", nullable = false)
	@Convert("booleanToByte")
	public boolean getIsprivate() {
		return this.isprivate;
	}

	public void setIsprivate(boolean isprivate) {
		this.isprivate = isprivate;
	}

	@Column(name = "isurl", nullable = false)
	@Convert("booleanToByte")
	public boolean getIsurl() {
		return this.isurl;
	}

	public void setIsurl(boolean isurl) {
		this.isurl = isurl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attachments")
	public Set<Flags> getFlagses() {
		return this.flagses;
	}

	public void setFlagses(Set<Flags> flagses) {
		this.flagses = flagses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attachment")
	public Set<TaskActivity> getTaskActivities() {
		return this.taskActivities;
	}

	public void setTaskActivities(Set<TaskActivity> taskActivities) {
		this.taskActivities = taskActivities;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "attachment")
	public AttachmentData getAttachData() {
		return this.attachData;
	}

	public void setAttachData(AttachmentData attachData) {
		this.attachData = attachData;
	}

	@PrePersist
	public void prePersist() {
		fillCreationTs();
		fillModificationTs();
	}

	private void fillModificationTs() {
		modificationTime = new Date();

	}

	private void fillCreationTs() {
		if (creationTs == null) {
			creationTs = new Date();
		}
	}

}
