/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CategoryGroupMap generated by hbm2java
 */
@Entity
@Table(name = "category_group_map", uniqueConstraints = @UniqueConstraint(columnNames = { "category_id", "group_id" }))
@SuppressWarnings("serial")
public class CategoryGroupMap implements java.io.Serializable {

	private CategoryGroupMapId id;
	private Group groups;
	private SeriesCategories seriesCategories;

	public CategoryGroupMap() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false)) })
	public CategoryGroupMapId getId() {
		return this.id;
	}

	public void setId(CategoryGroupMapId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false, insertable = false, updatable = false)
	public Group getGroups() {
		return this.groups;
	}

	public void setGroups(Group groups) {
		this.groups = groups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false, insertable = false, updatable = false)
	public SeriesCategories getSeriesCategories() {
		return this.seriesCategories;
	}

	public void setSeriesCategories(SeriesCategories seriesCategories) {
		this.seriesCategories = seriesCategories;
	}

}
