/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 25, 2010 7:09:56 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Duplicates generated by hbm2java
 */
@Entity
@Table(name = "duplicates")
@SuppressWarnings("serial")
public class Duplicate implements java.io.Serializable {

	private int dupe;
	private Task bugsByDupeOf;
	private Task bugsByBugId;

	public Duplicate() {
	}

	@Id
	@Column(name = "dupe", unique = true, nullable = false)
	public int getDupe() {
		return this.dupe;
	}

	public void setDupe(int dupe) {
		this.dupe = dupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dupe_of", nullable = false)
	public Task getBugsByDupeOf() {
		return this.bugsByDupeOf;
	}

	public void setBugsByDupeOf(Task bugsByDupeOf) {
		this.bugsByDupeOf = bugsByDupeOf;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Task getBugsByBugId() {
		return this.bugsByBugId;
	}

	public void setBugsByBugId(Task bugsByBugId) {
		this.bugsByBugId = bugsByBugId;
	}

	@PrePersist
	public void prePersist() {
		if (dupe == 0) {
			setDupe(getBugsByBugId().getId());
		}
	}

}
