/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.eclipse.persistence.annotations.Convert;

/**
 * EmailSettingId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class EmailSettingId implements java.io.Serializable {

	private int userId;
	private boolean relationship;
	private boolean event;

	public EmailSettingId() {
	}

	public EmailSettingId(int userId, boolean relationship, boolean event) {
		this.userId = userId;
		this.relationship = relationship;
		this.event = event;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "relationship", nullable = false)
	@Convert("booleanToByte")
	public boolean getRelationship() {
		return this.relationship;
	}

	public void setRelationship(boolean relationship) {
		this.relationship = relationship;
	}

	@Column(name = "event", nullable = false)
	@Convert("booleanToByte")
	public boolean getEvent() {
		return this.event;
	}

	public void setEvent(boolean event) {
		this.event = event;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (event ? 1231 : 1237);
		result = prime * result + (relationship ? 1231 : 1237);
		result = prime * result + userId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EmailSettingId other = (EmailSettingId) obj;
		if (event != other.event)
			return false;
		if (relationship != other.relationship)
			return false;
		if (userId != other.userId)
			return false;
		return true;
	}

}
