/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FlagexclusionsId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class FlagexclusionsId implements java.io.Serializable {

	private short typeId;
	private Short productId;
	private Short componentId;

	public FlagexclusionsId() {
	}

	public FlagexclusionsId(short typeId) {
		this.typeId = typeId;
	}

	public FlagexclusionsId(short typeId, Short productId, Short componentId) {
		this.typeId = typeId;
		this.productId = productId;
		this.componentId = componentId;
	}

	@Column(name = "type_id", nullable = false)
	public short getTypeId() {
		return this.typeId;
	}

	public void setTypeId(short typeId) {
		this.typeId = typeId;
	}

	@Column(name = "product_id")
	public Short getProductId() {
		return this.productId;
	}

	public void setProductId(Short productId) {
		this.productId = productId;
	}

	@Column(name = "component_id")
	public Short getComponentId() {
		return this.componentId;
	}

	public void setComponentId(Short componentId) {
		this.componentId = componentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlagexclusionsId))
			return false;
		FlagexclusionsId castOther = (FlagexclusionsId) other;

		return (this.getTypeId() == castOther.getTypeId())
				&& ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
						&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
				&& ((this.getComponentId() == castOther.getComponentId()) || (this.getComponentId() != null
						&& castOther.getComponentId() != null && this.getComponentId().equals(
						castOther.getComponentId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTypeId();
		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + (getComponentId() == null ? 0 : this.getComponentId().hashCode());
		return result;
	}

}
