/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.eclipse.persistence.annotations.Convert;

/**
 * GroupControlMapId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class GroupControlMapId implements java.io.Serializable {

	private int groupId;
	private short productId;
	private boolean entry;
	private boolean membercontrol;
	private boolean othercontrol;
	private boolean canedit;
	private boolean editcomponents;
	private boolean editbugs;
	private boolean canconfirm;

	public GroupControlMapId() {
	}

	public GroupControlMapId(int groupId, short productId, boolean entry, boolean membercontrol, boolean othercontrol,
			boolean canedit, boolean editcomponents, boolean editbugs, boolean canconfirm) {
		this.groupId = groupId;
		this.productId = productId;
		this.entry = entry;
		this.membercontrol = membercontrol;
		this.othercontrol = othercontrol;
		this.canedit = canedit;
		this.editcomponents = editcomponents;
		this.editbugs = editbugs;
		this.canconfirm = canconfirm;
	}

	@Column(name = "group_id", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "product_id", nullable = false)
	public short getProductId() {
		return this.productId;
	}

	public void setProductId(short productId) {
		this.productId = productId;
	}

	@Column(name = "entry", nullable = false)
	@Convert("booleanToByte")
	public boolean getEntry() {
		return this.entry;
	}

	public void setEntry(boolean entry) {
		this.entry = entry;
	}

	@Column(name = "membercontrol", nullable = false)
	@Convert("booleanToByte")
	public boolean getMembercontrol() {
		return this.membercontrol;
	}

	public void setMembercontrol(boolean membercontrol) {
		this.membercontrol = membercontrol;
	}

	@Column(name = "othercontrol", nullable = false)
	@Convert("booleanToByte")
	public boolean getOthercontrol() {
		return this.othercontrol;
	}

	public void setOthercontrol(boolean othercontrol) {
		this.othercontrol = othercontrol;
	}

	@Column(name = "canedit", nullable = false)
	@Convert("booleanToByte")
	public boolean getCanedit() {
		return this.canedit;
	}

	public void setCanedit(boolean canedit) {
		this.canedit = canedit;
	}

	@Column(name = "editcomponents", nullable = false)
	@Convert("booleanToByte")
	public boolean getEditcomponents() {
		return this.editcomponents;
	}

	public void setEditcomponents(boolean editcomponents) {
		this.editcomponents = editcomponents;
	}

	@Column(name = "editbugs", nullable = false)
	@Convert("booleanToByte")
	public boolean getEditbugs() {
		return this.editbugs;
	}

	public void setEditbugs(boolean editbugs) {
		this.editbugs = editbugs;
	}

	@Column(name = "canconfirm", nullable = false)
	@Convert("booleanToByte")
	public boolean getCanconfirm() {
		return this.canconfirm;
	}

	public void setCanconfirm(boolean canconfirm) {
		this.canconfirm = canconfirm;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (canconfirm ? 1231 : 1237);
		result = prime * result + (canedit ? 1231 : 1237);
		result = prime * result + (editbugs ? 1231 : 1237);
		result = prime * result + (editcomponents ? 1231 : 1237);
		result = prime * result + (entry ? 1231 : 1237);
		result = prime * result + groupId;
		result = prime * result + (membercontrol ? 1231 : 1237);
		result = prime * result + (othercontrol ? 1231 : 1237);
		result = prime * result + productId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GroupControlMapId other = (GroupControlMapId) obj;
		if (canconfirm != other.canconfirm)
			return false;
		if (canedit != other.canedit)
			return false;
		if (editbugs != other.editbugs)
			return false;
		if (editcomponents != other.editcomponents)
			return false;
		if (entry != other.entry)
			return false;
		if (groupId != other.groupId)
			return false;
		if (membercontrol != other.membercontrol)
			return false;
		if (othercontrol != other.othercontrol)
			return false;
		if (productId != other.productId)
			return false;
		return true;
	}

}
