/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GroupGroupMap generated by hbm2java
 */
@Entity
@Table(name = "group_group_map", uniqueConstraints = @UniqueConstraint(columnNames = { "member_id", "grantor_id",
		"grant_type" }))
@SuppressWarnings("serial")
public class GroupGroupMap implements java.io.Serializable {

	private GroupGroupMapId id;
	private Group groupsByMemberId;
	private Group groupsByGrantorId;

	public GroupGroupMap() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "memberId", column = @Column(name = "member_id", nullable = false)),
			@AttributeOverride(name = "grantorId", column = @Column(name = "grantor_id", nullable = false)),
			@AttributeOverride(name = "grantType", column = @Column(name = "grant_type", nullable = false)) })
	public GroupGroupMapId getId() {
		return this.id;
	}

	public void setId(GroupGroupMapId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false, insertable = false, updatable = false)
	public Group getGroupsByMemberId() {
		return this.groupsByMemberId;
	}

	public void setGroupsByMemberId(Group groupsByMemberId) {
		this.groupsByMemberId = groupsByMemberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grantor_id", nullable = false, insertable = false, updatable = false)
	public Group getGroupsByGrantorId() {
		return this.groupsByGrantorId;
	}

	public void setGroupsByGrantorId(Group groupsByGrantorId) {
		this.groupsByGrantorId = groupsByGrantorId;
	}

}
