/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GroupControlMap generated by hbm2java
 */
@Entity
@Table(name = "group_control_map", uniqueConstraints = @UniqueConstraint(columnNames = { "product_id", "group_id" }))
@SuppressWarnings("serial")
public class GroupControlMap implements java.io.Serializable {

	private GroupControlMapId id;
	private Group groups;
	private Product products;

	public GroupControlMap() {
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "entry", column = @Column(name = "entry", nullable = false)),
			@AttributeOverride(name = "membercontrol", column = @Column(name = "membercontrol", nullable = false)),
			@AttributeOverride(name = "othercontrol", column = @Column(name = "othercontrol", nullable = false)),
			@AttributeOverride(name = "canedit", column = @Column(name = "canedit", nullable = false)),
			@AttributeOverride(name = "editcomponents", column = @Column(name = "editcomponents", nullable = false)),
			@AttributeOverride(name = "editbugs", column = @Column(name = "editbugs", nullable = false)),
			@AttributeOverride(name = "canconfirm", column = @Column(name = "canconfirm", nullable = false)) })
	public GroupControlMapId getId() {
		return this.id;
	}

	public void setId(GroupControlMapId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false, insertable = false, updatable = false)
	public Group getGroups() {
		return this.groups;
	}

	public void setGroups(Group groups) {
		this.groups = groups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProducts() {
		return this.products;
	}

	public void setProducts(Product products) {
		this.products = products;
	}

}
