/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Keywords generated by hbm2java
 */
@Entity
@Table(name = "keywords", uniqueConstraints = @UniqueConstraint(columnNames = { "bug_id", "keywordid" }))
@SuppressWarnings("serial")
public class Keyword implements Serializable {

	private KeywordId id;
	private Task task;
	private Keyworddef keyworddef;

	public Keyword() {
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "bugId", column = @Column(name = "bug_id", nullable = false)),
			@AttributeOverride(name = "keywordid", column = @Column(name = "keywordid", nullable = false)) })
	public KeywordId getId() {
		return this.id;
	}

	public void setId(KeywordId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bug_id", nullable = false, insertable = false, updatable = false)
	public Task getBugs() {
		return this.task;
	}

	public void setBugs(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "keywordid", nullable = false, insertable = false, updatable = false)
	public Keyworddef getKeyworddefs() {
		return this.keyworddef;
	}

	public void setKeyworddefs(Keyworddef keyworddefs) {
		this.keyworddef = keyworddefs;
	}

}
