/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.eclipse.persistence.annotations.Convert;

/**
 * Resolution generated by hbm2java
 */
@Entity
@Table(name = "resolution")
@SuppressWarnings("serial")
public class Resolution extends AbstractReferenceEntity {

	private boolean isactive;
	private Short visibilityValueId;

	public Resolution() {
	}

	@Column(name = "isactive", nullable = false)
	@Convert("booleanToByte")
	public boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	@Column(name = "visibility_value_id")
	public Short getVisibilityValueId() {
		return this.visibilityValueId;
	}

	public void setVisibilityValueId(Short visibilityValueId) {
		this.visibilityValueId = visibilityValueId;
	}

}
