/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeriesDataId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class SeriesDataId implements java.io.Serializable {

	private int seriesId;
	private Date seriesDate;
	private int seriesValue;

	public SeriesDataId() {
	}

	public SeriesDataId(int seriesId, Date seriesDate, int seriesValue) {
		this.seriesId = seriesId;
		this.seriesDate = seriesDate;
		this.seriesValue = seriesValue;
	}

	@Column(name = "series_id", nullable = false)
	public int getSeriesId() {
		return this.seriesId;
	}

	public void setSeriesId(int seriesId) {
		this.seriesId = seriesId;
	}

	@Column(name = "series_date", nullable = false, length = 19)
	@Temporal(TemporalType.TIMESTAMP)
	public Date getSeriesDate() {
		return this.seriesDate;
	}

	public void setSeriesDate(Date seriesDate) {
		this.seriesDate = seriesDate;
	}

	@Column(name = "series_value", nullable = false)
	public int getSeriesValue() {
		return this.seriesValue;
	}

	public void setSeriesValue(int seriesValue) {
		this.seriesValue = seriesValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeriesDataId))
			return false;
		SeriesDataId castOther = (SeriesDataId) other;

		return (this.getSeriesId() == castOther.getSeriesId())
				&& ((this.getSeriesDate() == castOther.getSeriesDate()) || (this.getSeriesDate() != null
						&& castOther.getSeriesDate() != null && this.getSeriesDate().equals(castOther.getSeriesDate())))
				&& (this.getSeriesValue() == castOther.getSeriesValue());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSeriesId();
		result = 37 * result + (getSeriesDate() == null ? 0 : this.getSeriesDate().hashCode());
		result = 37 * result + this.getSeriesValue();
		return result;
	}

}
