/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SettingValueId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class SettingValueId implements java.io.Serializable {

	private String name;
	private String value;
	private short sortindex;

	public SettingValueId() {
	}

	public SettingValueId(String name, String value, short sortindex) {
		this.name = name;
		this.value = value;
		this.sortindex = sortindex;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", nullable = false, length = 32)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "sortindex", nullable = false)
	public short getSortindex() {
		return this.sortindex;
	}

	public void setSortindex(short sortindex) {
		this.sortindex = sortindex;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SettingValueId))
			return false;
		SettingValueId castOther = (SettingValueId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this
				.getName().equals(castOther.getName())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())))
				&& (this.getSortindex() == castOther.getSortindex());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result + this.getSortindex();
		return result;
	}

}
