/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BugsActivity generated by hbm2java
 */
@Entity
@Table(name = "bugs_activity")
@SuppressWarnings("serial")
public class TaskActivity implements java.io.Serializable {

	private TaskActivityId id;
	private Task bugs;
	private Attachment attachment;
	private Profile profiles;
	private Fielddef fielddefs;

	public TaskActivity() {
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "bugId", column = @Column(name = "bug_id", nullable = false)),
			@AttributeOverride(name = "who", column = @Column(name = "who", nullable = false)),
			@AttributeOverride(name = "bugWhen", column = @Column(name = "bug_when", nullable = false, length = 19)),
			@AttributeOverride(name = "fieldid", column = @Column(name = "fieldid", nullable = false)),
			@AttributeOverride(name = "added", column = @Column(name = "added")),
			@AttributeOverride(name = "removed", column = @Column(name = "removed")) })
	public TaskActivityId getId() {
		return this.id;
	}

	public void setId(TaskActivityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bug_id", nullable = false, insertable = false, updatable = false)
	public Task getBugs() {
		return this.bugs;
	}

	public void setBugs(Task bugs) {
		this.bugs = bugs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attach_id", insertable = false, updatable = false)
	public Attachment getAttachment() {
		return this.attachment;
	}

	public void setAttachment(Attachment attachment) {
		this.attachment = attachment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "who", nullable = false, insertable = false, updatable = false)
	public Profile getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Profile profiles) {
		this.profiles = profiles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fieldid", nullable = false, insertable = false, updatable = false)
	public Fielddef getFielddefs() {
		return this.fielddefs;
	}

	public void setFielddefs(Fielddef fielddefs) {
		this.fielddefs = fielddefs;
	}

	@Override
	public String toString() {
		return "TaskActivity [field=" + fielddefs.getName() + ", removed=" + id.getRemoved() + ", added="
				+ id.getAdded() + "]";
	}

}
