/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tokens generated by hbm2java
 */
@Entity
@Table(name = "tokens")
@SuppressWarnings("serial")
public class Token implements java.io.Serializable {

	private String token;
	private Profile profiles;
	private Date issuedate;
	private String tokentype;
	private String eventdata;

	public Token() {
	}

	@Id
	@Column(name = "token", unique = true, nullable = false, length = 16)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Profile getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Profile profiles) {
		this.profiles = profiles;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "issuedate", nullable = false, length = 19)
	public Date getIssuedate() {
		return this.issuedate;
	}

	public void setIssuedate(Date issuedate) {
		this.issuedate = issuedate;
	}

	@Column(name = "tokentype", nullable = false, length = 8)
	public String getTokentype() {
		return this.tokentype;
	}

	public void setTokentype(String tokentype) {
		this.tokentype = tokentype;
	}

	@Column(name = "eventdata")
	public String getEventdata() {
		return this.eventdata;
	}

	public void setEventdata(String eventdata) {
		this.eventdata = eventdata;
	}

}
