/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TsErrorId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class TsErrorId implements java.io.Serializable {

	private int errorTime;
	private int jobid;
	private String message;
	private int funcid;

	public TsErrorId() {
	}

	public TsErrorId(int errorTime, int jobid, String message, int funcid) {
		this.errorTime = errorTime;
		this.jobid = jobid;
		this.message = message;
		this.funcid = funcid;
	}

	@Column(name = "error_time", nullable = false)
	public int getErrorTime() {
		return this.errorTime;
	}

	public void setErrorTime(int errorTime) {
		this.errorTime = errorTime;
	}

	@Column(name = "jobid", nullable = false)
	public int getJobid() {
		return this.jobid;
	}

	public void setJobid(int jobid) {
		this.jobid = jobid;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "funcid", nullable = false)
	public int getFuncid() {
		return this.funcid;
	}

	public void setFuncid(int funcid) {
		this.funcid = funcid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TsErrorId))
			return false;
		TsErrorId castOther = (TsErrorId) other;

		return (this.getErrorTime() == castOther.getErrorTime())
				&& (this.getJobid() == castOther.getJobid())
				&& ((this.getMessage() == castOther.getMessage()) || (this.getMessage() != null
						&& castOther.getMessage() != null && this.getMessage().equals(castOther.getMessage())))
				&& (this.getFuncid() == castOther.getFuncid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getErrorTime();
		result = 37 * result + this.getJobid();
		result = 37 * result + (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result + this.getFuncid();
		return result;
	}

}
