/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.internal.tasks.domain;

// Generated May 26, 2010 11:31:55 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VotesId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class VoteId implements java.io.Serializable {

	private int who;
	private int bugId;
	private short voteCount;

	public VoteId() {
	}

	public VoteId(int who, int bugId, short voteCount) {
		this.who = who;
		this.bugId = bugId;
		this.voteCount = voteCount;
	}

	@Column(name = "who", nullable = false)
	public int getWho() {
		return this.who;
	}

	public void setWho(int who) {
		this.who = who;
	}

	@Column(name = "bug_id", nullable = false)
	public int getBugId() {
		return this.bugId;
	}

	public void setBugId(int bugId) {
		this.bugId = bugId;
	}

	@Column(name = "vote_count", nullable = false)
	public short getVoteCount() {
		return this.voteCount;
	}

	public void setVoteCount(short voteCount) {
		this.voteCount = voteCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VoteId))
			return false;
		VoteId castOther = (VoteId) other;

		return (this.getWho() == castOther.getWho()) && (this.getBugId() == castOther.getBugId())
				&& (this.getVoteCount() == castOther.getVoteCount());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWho();
		result = 37 * result + this.getBugId();
		result = 37 * result + this.getVoteCount();
		return result;
	}

}
