/*******************************************************************************
 * Copyright (c) 2010, 2012 Tasktop Technologies
 * Copyright (c) 2010, 2011 SpringSource, a division of VMware
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 ******************************************************************************/
package com.tasktop.c2c.server.monitoring.service;

import com.tasktop.c2c.server.monitoring.domain.MonitoringEvent;

/**
 * Service which process {@link MonitoringEvent}s. Typically these events would be generated by a slow repose or
 * exception on a project's deployment. The service would then create or update a task to track the issue.
 * 
 * @author Clint Morgan <clint.morgan@tasktop.com> (Tasktop Technologies Inc.)
 * 
 */
public interface MonitoringService {
	void processEvent(MonitoringEvent event);
}
